### ISSUE TITLE
Warning: Prop `className` did not match. Server: "navbar-item is-hidden" Client: "navbar-item"

### ISSUE THREAD

**Issue by IRediTOTO** [sergiodxa/swr-sync-storage#28]
Hi, I have this error when check user data in. Did you face with this problem? 

```Warning: Prop `className` did not match. Server: "navbar-item is-hidden" Client: "navbar-item"```

```
 <Link href="/user" as="/user">
     <a  className={ user? "navbar-item" : "navbar-item is-hidden" }>
           Dashboard
     </a>
</Link>
```

**Comment by IRediTOTO** [comment]
i fixed it by use `useEffect` 
```
const { currentUser } = useCurrentUser();
   let user= null
   useEffect(()=>{
      if(currentUser){
         user=currentUser
      }
   },[currentUser])
```
Can you fix your to get smooth code? Or is this from my error?

**Comment by IRediTOTO** [comment]
I tried to `npm run build` No error apear. Look like this just show on dev.

**Comment by sergiodxa** [comment]
This is happening because with this package now you have the data already in the cache so React renders with user already defined, but server-side you don't have data so React renders with user as undefined, Your effect solution should work, but you will need to save it in a state or ref and not a variable, is variable is not going to work because on each render it will be go back to be undefined and a change will not trigger a new render.
